on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: https://example.invalid/REDACTED_SLACK_WEBHOOK
        SLACK_CHANNEL: stock-management
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'GitHub Action has completed with status: ${{ job.status }}'
        SLACK_TITLE: '${{github.workflow}} - ${{ job.status }}'
        SLACK_USERNAME: schedule-executor-notifier